### ISSUE TITLE
Bug(Calling): Clicking notification resets call duration

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#557]
### Developement Issue

No

### Phone Version

Latest master

### Issue Description

When in call, clicking the notification header at the top resets duration.

### Issue Reproduction

1. Start call
2. Someone accepts
3. Click notification header

Time will restart.

### Evidence
![image](https://user-images.githubusercontent.com/55056068/150381563-1ba37199-d8a6-4f59-858d-836d51ad57db.png)

**Comment by Deniel00** [comment]
it's fixed in v1.2.7
![kép](https://user-images.githubusercontent.com/12788940/160641088-aeebbe77-54ee-4b95-9ab9-40bf33365474.png)
![kép](https://user-images.githubusercontent.com/12788940/160641126-f4d7a080-4dfb-48f9-baca-2ba3234649eb.png)
![kép](https://user-images.githubusercontent.com/12788940/160641158-bcab71ba-81c2-4e35-9e34-498b30af961b.png)

**Comment by itschip** [comment]
Closing this we're removing the notification.
