### ISSUE TITLE
Bug: Conversation names with custom numbers

### ISSUE THREAD

**Issue by AvaN0x** [project-error/npwd#591]
### Development Issue

Yes

### Phone Version

Release 1.1.5

### Issue Description

Issue when parsing non existing numbers|names for conversations.
Also this break new `onMessage` exports, the number seem to be considered as different.

There is also this error log when creating a conversation with a custom number (here `911`) : 
![image](https://user-images.githubusercontent.com/27494805/152874885-017a93d1-c73b-4d00-bbd6-4c3ec5d12a53.png)

### Issue Reproduction

For these steps, my number is `456-456-4567`
1. Create a conversation and send message to any number, in this case I used `911`
![image](https://user-images.githubusercontent.com/27494805/152872707-4205fe30-fa69-4c24-816a-8a49c52cca97.png)
1. Disconnected and reconnected to the server (restarting the phone and calling the exports to load user should do the same)
1. The conversation is now be named after your phone number and all messages seem to be unread
![image](https://user-images.githubusercontent.com/27494805/152872790-dce558ca-31f8-4d99-9c90-f5b6f57f36ae.png)

**Comment by RockySouthpaw** [comment]
To provide the additional information to this issue:

You’re missing another debug print because @itschip made the log level be debug only. There is a print here that states that’s probably a service number. 

![13997A7C-B808-413C-A453-B336B94552F7](https://user-images.githubusercontent.com/55056068/152898882-41cc23ae-0498-4f05-8e68-fb3c070c6cff.png)

The issue here is due to the way @itschip or @jfrader did the SQL logic for messages as it’s overly complicated and generally pretty messy. We seem to be doing a query for inserting the source number twice: https://github.com/project-error/npwd/blob/474d49007faef383b29642c46785946be81bf51f/resources/server/messages/messages.utils.ts#L114

**Comment by AvaN0x** [comment]
> You’re missing another debug ... There is a print here that states that’s probably a service number.

Oh yes my bad, moved to `silly` and I have it now. I will think about it next time.

**Comment by itschip** [comment]
Time to rewrite.

**Comment by itschip** [comment]
I'll keep this open until we merge the message rewrite to master.

**Comment by itschip** [comment]
@AvaN0x closing this. Please let me know if it still occurs.

**Comment by AvaN0x** [comment]
Seem to have been fixed! 👍 
I will let you know if it occurs again.
