### ISSUE TITLE
Enhancement: Send location through messages

### ISSUE THREAD

**Issue by itschip** [project-error/npwd#711]
### Application

Messages

### Dependency

No

### Feature Description

New context menu option to send your current coords through messages. Coords should not update over time.

**Comment by AvaN0x** [comment]
Hello, I have just been looking at the code for embeds (mainly for the shared locations) and I was wondering something:
What would think about displaying the message content next to the shared location?

I'm asking this because from what I see, the [MessageEmbed](https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/ui/MessageEmbed.tsx#L23) (and so [LocationEmbed ](https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/ui/MessageEmbed.tsx#L63)) only has informations about the embed part of the message:
https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/ui/MessageEmbed.tsx#L23
and even though the string `MESSAGES.LOCATION_MESSAGE` is sent as message content:
https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/modal/MessageContextMenu.tsx#L68
this string will never get used because the embed is made to display `MESSAGES.LOCATION_MESSAGE` (so you can edit the message content in the database and nothing will change):
https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/ui/MessageEmbed.tsx#L75

This would allow to send custom messages with locations through `emitMessage`, and could make the "Share location" button use the currently inputed text as message content or default to `MESSAGES.LOCATION_MESSAGE`.

Example of what it could look like: 
![image](https://user-images.githubusercontent.com/27494805/162399440-3897d5f9-483b-4b94-95df-b78d19ed896d.png)
*Disclaimer: I edited this with the devtools to see what it could look like*

**Comment by Mojito-Fivem** [comment]
> That's why, even though the string `MESSAGES.LOCATION_MESSAGE` is sent as message content:
> https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/modal/MessageContextMenu.tsx#L68
> 
> 
> this string will never get used because the embed is made to display `MESSAGES.LOCATION_MESSAGE` (so you can edit the message content in the database and nothing will change):

This is done so that the notifications aren't blank, this fix has also been applied to contact embeds.

**Comment by AvaN0x** [comment]
> > That's why, even though the string `MESSAGES.LOCATION_MESSAGE` is sent as message content:
> > https://github.com/project-error/npwd/blob/481110f3710212f3dbe8e5672ac4163bf8c41d1b/phone/src/apps/messages/components/modal/MessageContextMenu.tsx#L68
> > 
> > this string will never get used because the embed is made to display `MESSAGES.LOCATION_MESSAGE` (so you can edit the message content in the database and nothing will change):
> 
> This is done so that the notifications aren't blank, this fix has also been applied to contact embeds.

Oh okay, I didn't think about the notifications.
