### ISSUE TITLE
Phone number change or default phone number

### ISSUE THREAD

**Issue by OuOwei** [project-error/npwd#743]
### Application

Other

### Dependency

No

### Feature Description

I don't want to have such a long phone number, I want to be able to change the phone number length.

**Comment by DarinBeard** [comment]
If you are comfortable messing in the code, in server.js search for generateUsNumber and you can change how it generates the number there. I modified it to be only 7 digits and formatted it nnn-nnnn instead of the 10 digit. That worked for us. But I wouldn't mess with it if you aren't comfortable with it.

**Comment by Mojito-Fivem** [comment]
> If you are comfortable messing in the code, in server.js search for generateUsNumber and you can change how it generates the number there. I modified it to be only 7 digits and formatted it nnn-nnnn instead of the 10 digit. That worked for us. But I wouldn't mess with it if you aren't comfortable with it.

[This](https://github.com/project-error/npwd/blob/8bec2f254dc57f18f9964df60538df0db2446124/resources/server/misc/generateUniquePhoneNumber.ts#L27) Is where we handle generating numbers. download the source, make your changes and build. *do not* edit your bundle files
