### ISSUE TITLE
Bug: onMessage

### ISSUE THREAD

**Issue by frazz1234** [project-error/npwd#802]
### Development Issue

Yes

### Phone Version

Last one

### Issue Description

Im using this export : 

```lua
exports.npwd:onMessage('911', function(ctx)
    local sendernmbr = exports.npwd:getPhoneNumber(ctx.source)
    local police = ESX.GetExtendedPlayers('job','police')
    for i = 1, #police do
        local targetnmbr = exports.npwd:getPhoneNumber(police[i].playerId)
        exports.npwd:emitMessage({
            senderNumber = sendernmbr,
            targetNumber = targetnmbr,
            message = ctx.data.message,
        })                
    end
end)
```

![20220709012344_1](https://user-images.githubusercontent.com/66176776/178092885-8850a8db-1cb6-4209-a73e-b8530baeb763.jpg)

direct after receive this message in my phone i got this error : 
![20220709012406_1](https://user-images.githubusercontent.com/66176776/178092887-f29aec0a-489f-4cea-96a3-822938fc3a67.jpg)

### Issue Reproduction

apply the export you will see

**Comment by frazz1234** [comment]
this error still going  if i press on the empty message

**Comment by Mojito-Fivem** [comment]
can you provide a framework agnostic reproduction since none of our developers are using ESX

**Comment by frazz1234** [comment]
Im using the legacy one, https://github.com/esx-framework/esx-legacy

**Comment by itschip** [comment]
Try `exports.npwd:getPhoneNumber(police[i].source)`

**Comment by frazz1234** [comment]
I will try it today.

I see an other bug, I'm using ESX legacy like I told you and ox inventory , I have everything set up good.

But if I'm connect and I don't have the phone I can receive notifications from my phone when someone call. I can't answer.

**Comment by SamShanks1** [comment]
@frazz1234 did chips change fix the erro?

**Comment by ItzTrivial** [comment]
Hello, Ive already wrote something on PE discord, but I wanted to make it official here too:
Thats my snippet and I know the error. The problem here is, that if you are police yourself you are receiving the message you send to the police yourself. So if you are texting a message to 911 not only will the message appear in the 911 chat, but you will send YOURSELF a message with that. Clicking on one of the empty chats will show you this error, since npwd isnt able to create a message-conversation with yourself. 

For everyone in need of that snippet, because they want a possibility for the police to get messages rp-wise Id recommend to take a look at Mojitos npwd-dispatch script, which utilizes exactly that, just way better and smarter.
