### ISSUE TITLE
Bug: Phone text fields

### ISSUE THREAD

**Issue by Demigod916** [project-error/npwd#830]
### Development Issue

No

### Phone Version

1.4.0

### Issue Description

when exiting the phone while some text fields are focused, the game will think that you have left click held down until you click again. seems like the game is out of focus or something.

### Issue Reproduction

1. open phone
2. go to twitter
3. go to twitter profile settings
4. click on one of the text fields for name or image
5. while still focused on the text field, close the phone using esc
6. equip gun
7. starts shooting on its own

### Evidence

https://streamable.com/dbeywm

**Comment by menkzy** [comment]
I can also repro this. 
https://github.com/project-error/pe-core

**Comment by kylemcshea** [comment]
I have this issue as well on my end.

-- Bug Report #1 --
"when u text on ur phone and then pull out ur gun it'll auto fire so something with the text messages on the phone is causing it however when u text and put the phone away get in a car and press left mouse button it'll fix it"

-- Bug Report #2 --
"My weapon will fire on its own as soon as I pull it out after using my phone. I would like some help on this situation so that people don't think that I'm trying to shoot at somebody for no reason and catch a Bahama"

-- Attached below is the clip from bug report #1 --
https://cdn.discordapp.com/attachments/999897088273961030/1002537511295397888/2022-07-29_12-24-13_Trim.mp4

**Comment by menkzy** [comment]
Just realised my copy+paste didnt post the correct link.

**Comment by itschip** [comment]
Thanks for the report :)

**Comment by itschip** [comment]
Fixed in develop
